spring:
  application:
    name: auth-service
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: money-management
      port: 27017
  mail:
    host: smtp.gmail.com
    port: 465
    username: moneymanagement94
    password: MoneyManagement94
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 98680346203-ocda096fo3f27enrbcotphf7i0mituqh.apps.googleusercontent.com
            client-secret: sBEbZZgRAM04cjF4T0Mv3ZPb
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            client-id: 301931163845796
            client-secret: d1a7d45545b703b0034c64be457f6414
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
  rabbitmq:
    host: rabbitmq
  main:
    allow-bean-definition-overriding: true


app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris: http://auth-service:5000/uaa/oauth2/redirect

server:
  servlet:
    context-path: /uaa
  port: 5000

logging:
  level:
    org.springframework.security: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current

verification:
  email:
    subject: "Verification email"
    text: "Hello, \n Bellow you have the email verification address. \n  {0} \r\n\r\nCheers,\r\nMoney Management team"
    url: "http://localhost:80/uaa/users/verification?token="

forgot-password:
  email:
    subject: "Forgot Password email"
    text: "Hello, \n Bellow you have the link to reset your password, \n {0} \r\n\r\nCheers,\r\nMoney Management team"
    url: "http://localhost:4200/reset-password?token="

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
