spring:
  application:
    name: registry
  rabbitmq:
    host: rabbitmq

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
          defaultZone: http://registry:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    org.springframework.security: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000