spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: money-management
      port: 27017

server:
  context-path: /uaa
  port: 5000
