spring:
  application:
    name: account-service
  data:
    mongodb:
      host: account-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: money-management
      port: 27017
  rabbitmq:
    host: rabbitmq
  main:
    allow-bean-definition-overriding: true

security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current

server:
  servlet:
    context-path: /accounts
  port: 6000

logging:
  level:
    org.springframework.security: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000